package org.fi.muni.diploma.thesis.service_lifecycle_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Service implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

  // @org.kie.api.definition.type.Position(value = 0)
   private java.lang.String name;

  // @org.kie.api.definition.type.Position(value = 1)
  // @javax.persistence.Id
   private java.lang.String UUID;

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getUUID()
   {
      return this.UUID;
   }

   public void setUUID(java.lang.String UUID)
   {
      this.UUID = UUID;
   }

   public Service()
   {
   }

   public Service(java.lang.String name, java.lang.String UUID)
   {
      this.name = name;
      this.UUID = UUID;
   }
   
   public String toString()
{
return this.UUID + "#" + this.name + "#";
}

}
